### PR TITLE
Fixes: #41 Adds --no-use-binaries option

### PR DESCRIPTION
**Pull request by kylebrowning**

### CODE REVIEW

**Comment by NachoSoto** [comment]
I wouldn't make this the default, as binaries can greatly speed up the process (if they're compatible).

I'd propose adding an option to allow users to choose this.

**Comment by kylebrowning** [comment]
Thats a good point, but not sure how to fix this gem to support downloading frameworks because its doesn't seem to be working. See #41

**Comment by segiddins** [comment]
I agree this needs to be an option

**Comment by kylebrowning** [comment]
Well I tested it locally and it actually doesn't fix the issue.

```
in/carthage-play acquia/waterwheel-swift --verbose
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/executable.rb:69:in `execute_command': [!] /usr/local/bin/carthage update --platform ios --no-use-binaries (Pod::Informative)

*** Fetching waterwheel-swift
*** Fetching SwiftyJSON
*** Fetching ObjectMapper
*** Fetching SwiftyUserDefaults
*** Fetching Alamofire
*** Checking out Alamofire at "4.0.1"
*** Checking out ObjectMapper at "2.0.0"
*** Checking out SwiftyJSON at "3.1.0"
*** Checking out SwiftyUserDefaults at "3.0.0"
*** Checking out waterwheel-swift at "4.3.1"
A shell task (/usr/bin/env git checkout --quiet c0462747a546575665f57fceeb560b5d2830b36b) failed with exit code 128:
fatal: reference is not a tree: c0462747a546575665f57fceeb560b5d2830b36b
```

**Pull request closed without merging**
