### PR TITLE
Updated order of commands in README

### PR DESCRIPTION
**Pull request by KrauseFx**
You have to install the gem before you can use them

### CODE REVIEW

**Comment by neonichu** [comment]
That's a big `README` design question for me :) My reasoning for this order is that people want to see more info on what it does first before they install.

**Comment by KrauseFx** [comment]
I just asked my co-worker:

> Do I have to install software before I can use it

and he said yes.

**Comment by neonichu** [comment]
:trollface:

**Comment by neonichu** [comment]
¯\_(ツ)_/¯

**Comment by KrauseFx** [comment]
Oh yeah :+1:

**Pull request merged**
