### PR TITLE
Replace XCPlayground to new PlaygroundSupport

### PR DESCRIPTION
**Pull request by ronanrodrigo**

### CODE REVIEW

**Comment by segiddins** [comment]
What versions of Xcode does this support?

**Comment by ronanrodrigo** [comment]
@segiddins since Xcode 7

**Comment by segiddins** [comment]
Can you point to docs for that?

**Comment by ronanrodrigo** [comment]
Yes, sure :) https://developer.apple.com/reference/playgroundsupport

**Comment by segiddins** [comment]
Cool!

**Pull request merged**
