### PR TITLE
Carthage support

### LINKED ISSUE #3: Investigate building Playgrounds for Carthage-enabled libs
I'm thinking this should work fairly easy:
- Build using `carthage`
- Add binary frameworks to the generated project
- Make the generated target depend on them

When building the generated target, the dependent frameworks should end up in the Playground's framework search path.

### PR DESCRIPTION
**Pull request by neonichu**
Closes #3

This adds support for carthage :tada: 

``` markdown
### Carthage

To generate a Playground for a Carthage-enabled library:

    $ carthage-play Alamofire/Alamofire

Note: This currently assumes that libraries are hosted on GitHub.
```

### CODE REVIEW

**Comment by neonichu** [comment]
Would love to see some testing from folks who actually use Carthage before shipping this.

To test:
1. Clone this branch
2. Build using `rake build`
3. Install the gem using `[sudo] gem install pkg/cocoapods-playgrounds-0.0.3.gem`
4. Run e.g. `carthage-play Alamofire/Alamofire`

Maybe @NachoSoto or @JaviSoto are interested? :)

**Comment by NachoSoto** [comment]
I'll definitely test this soon! 😍

**Comment by mbuchetics** [comment]
It would be great if this would support a [Cartfile](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfile) as input as alternative to the command line arguments.

**Comment by neonichu** [comment]
@mbuchetics I like the idea, this is supported now. 

However, parsing the `Cartfile` felt like a bit too much magic, so this will name the Playground after the specified filename (so usually "CartfilePlayground") and will not auto-generate import statements.

**Comment by mbuchetics** [comment]
Awesome! Doing the imports manually is no problem, I agree that parsing the Cartfile is problematic.

**Comment by neonichu** [comment]
I'm gonna :shipit: — it works and can always be improved later.

**Pull request merged**
